// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_uploadPushToken.proto

package com.zaly.proto.platform;

public final class UploadPushToken {
  private UploadPushToken() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiPushTokenRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPushTokenRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id_pubk = 1;</code>
     */
    java.lang.String getUserIdPubk();
    /**
     * <code>string user_id_pubk = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();

    /**
     * <code>string user_device_pubk = 2;</code>
     */
    java.lang.String getUserDevicePubk();
    /**
     * <code>string user_device_pubk = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserDevicePubkBytes();

    /**
     * <code>string user_device_sign = 3;</code>
     */
    java.lang.String getUserDeviceSign();
    /**
     * <code>string user_device_sign = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceSignBytes();

    /**
     * <code>string push_token = 4;</code>
     */
    java.lang.String getPushToken();
    /**
     * <code>string push_token = 4;</code>
     */
    com.google.protobuf.ByteString
        getPushTokenBytes();
  }
  /**
   * Protobuf type {@code platform.ApiPushTokenRequest}
   */
  public  static final class ApiPushTokenRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiPushTokenRequest)
      ApiPushTokenRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApiPushTokenRequest.newBuilder() to construct.
    private ApiPushTokenRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPushTokenRequest() {
      userIdPubk_ = "";
      userDevicePubk_ = "";
      userDeviceSign_ = "";
      pushToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApiPushTokenRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPubk_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userDevicePubk_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceSign_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              pushToken_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest.class, com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest.Builder.class);
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 1;
    private volatile java.lang.Object userIdPubk_;
    /**
     * <code>string user_id_pubk = 1;</code>
     */
    public java.lang.String getUserIdPubk() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPubk_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id_pubk = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICE_PUBK_FIELD_NUMBER = 2;
    private volatile java.lang.Object userDevicePubk_;
    /**
     * <code>string user_device_pubk = 2;</code>
     */
    public java.lang.String getUserDevicePubk() {
      java.lang.Object ref = userDevicePubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDevicePubk_ = s;
        return s;
      }
    }
    /**
     * <code>string user_device_pubk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserDevicePubkBytes() {
      java.lang.Object ref = userDevicePubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDevicePubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICE_SIGN_FIELD_NUMBER = 3;
    private volatile java.lang.Object userDeviceSign_;
    /**
     * <code>string user_device_sign = 3;</code>
     */
    public java.lang.String getUserDeviceSign() {
      java.lang.Object ref = userDeviceSign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceSign_ = s;
        return s;
      }
    }
    /**
     * <code>string user_device_sign = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceSignBytes() {
      java.lang.Object ref = userDeviceSign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUSH_TOKEN_FIELD_NUMBER = 4;
    private volatile java.lang.Object pushToken_;
    /**
     * <code>string push_token = 4;</code>
     */
    public java.lang.String getPushToken() {
      java.lang.Object ref = pushToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pushToken_ = s;
        return s;
      }
    }
    /**
     * <code>string push_token = 4;</code>
     */
    public com.google.protobuf.ByteString
        getPushTokenBytes() {
      java.lang.Object ref = pushToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pushToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdPubk_);
      }
      if (!getUserDevicePubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userDevicePubk_);
      }
      if (!getUserDeviceSignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userDeviceSign_);
      }
      if (!getPushTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, pushToken_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdPubk_);
      }
      if (!getUserDevicePubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userDevicePubk_);
      }
      if (!getUserDeviceSignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userDeviceSign_);
      }
      if (!getPushTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, pushToken_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest)) {
        return super.equals(obj);
      }
      com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest other = (com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest) obj;

      boolean result = true;
      result = result && getUserIdPubk()
          .equals(other.getUserIdPubk());
      result = result && getUserDevicePubk()
          .equals(other.getUserDevicePubk());
      result = result && getUserDeviceSign()
          .equals(other.getUserDeviceSign());
      result = result && getPushToken()
          .equals(other.getPushToken());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPubk().hashCode();
      hash = (37 * hash) + USER_DEVICE_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserDevicePubk().hashCode();
      hash = (37 * hash) + USER_DEVICE_SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceSign().hashCode();
      hash = (37 * hash) + PUSH_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getPushToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiPushTokenRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPushTokenRequest)
        com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest.class, com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest.Builder.class);
      }

      // Construct using com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userIdPubk_ = "";

        userDevicePubk_ = "";

        userDeviceSign_ = "";

        pushToken_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenRequest_descriptor;
      }

      public com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest getDefaultInstanceForType() {
        return com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest.getDefaultInstance();
      }

      public com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest build() {
        com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest buildPartial() {
        com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest result = new com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest(this);
        result.userIdPubk_ = userIdPubk_;
        result.userDevicePubk_ = userDevicePubk_;
        result.userDeviceSign_ = userDeviceSign_;
        result.pushToken_ = pushToken_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest) {
          return mergeFrom((com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest other) {
        if (other == com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest.getDefaultInstance()) return this;
        if (!other.getUserIdPubk().isEmpty()) {
          userIdPubk_ = other.userIdPubk_;
          onChanged();
        }
        if (!other.getUserDevicePubk().isEmpty()) {
          userDevicePubk_ = other.userDevicePubk_;
          onChanged();
        }
        if (!other.getUserDeviceSign().isEmpty()) {
          userDeviceSign_ = other.userDeviceSign_;
          onChanged();
        }
        if (!other.getPushToken().isEmpty()) {
          pushToken_ = other.pushToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userIdPubk_ = "";
      /**
       * <code>string user_id_pubk = 1;</code>
       */
      public java.lang.String getUserIdPubk() {
        java.lang.Object ref = userIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id_pubk = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        java.lang.Object ref = userIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id_pubk = 1;</code>
       */
      public Builder clearUserIdPubk() {
        
        userIdPubk_ = getDefaultInstance().getUserIdPubk();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDevicePubk_ = "";
      /**
       * <code>string user_device_pubk = 2;</code>
       */
      public java.lang.String getUserDevicePubk() {
        java.lang.Object ref = userDevicePubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDevicePubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_device_pubk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserDevicePubkBytes() {
        java.lang.Object ref = userDevicePubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDevicePubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_device_pubk = 2;</code>
       */
      public Builder setUserDevicePubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDevicePubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_device_pubk = 2;</code>
       */
      public Builder clearUserDevicePubk() {
        
        userDevicePubk_ = getDefaultInstance().getUserDevicePubk();
        onChanged();
        return this;
      }
      /**
       * <code>string user_device_pubk = 2;</code>
       */
      public Builder setUserDevicePubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDevicePubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceSign_ = "";
      /**
       * <code>string user_device_sign = 3;</code>
       */
      public java.lang.String getUserDeviceSign() {
        java.lang.Object ref = userDeviceSign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceSign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_device_sign = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceSignBytes() {
        java.lang.Object ref = userDeviceSign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceSign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_device_sign = 3;</code>
       */
      public Builder setUserDeviceSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceSign_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_device_sign = 3;</code>
       */
      public Builder clearUserDeviceSign() {
        
        userDeviceSign_ = getDefaultInstance().getUserDeviceSign();
        onChanged();
        return this;
      }
      /**
       * <code>string user_device_sign = 3;</code>
       */
      public Builder setUserDeviceSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceSign_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pushToken_ = "";
      /**
       * <code>string push_token = 4;</code>
       */
      public java.lang.String getPushToken() {
        java.lang.Object ref = pushToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pushToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string push_token = 4;</code>
       */
      public com.google.protobuf.ByteString
          getPushTokenBytes() {
        java.lang.Object ref = pushToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pushToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string push_token = 4;</code>
       */
      public Builder setPushToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pushToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string push_token = 4;</code>
       */
      public Builder clearPushToken() {
        
        pushToken_ = getDefaultInstance().getPushToken();
        onChanged();
        return this;
      }
      /**
       * <code>string push_token = 4;</code>
       */
      public Builder setPushTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pushToken_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiPushTokenRequest)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiPushTokenRequest)
    private static final com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest();
    }

    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPushTokenRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiPushTokenRequest>() {
      public ApiPushTokenRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiPushTokenRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPushTokenRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPushTokenRequest> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.platform.UploadPushToken.ApiPushTokenRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiPushTokenResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.ApiPushTokenResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 res_code = 1;</code>
     */
    int getResCode();

    /**
     * <code>string res_data = 2;</code>
     */
    java.lang.String getResData();
    /**
     * <code>string res_data = 2;</code>
     */
    com.google.protobuf.ByteString
        getResDataBytes();

    /**
     * <code>string err_info = 3;</code>
     */
    java.lang.String getErrInfo();
    /**
     * <code>string err_info = 3;</code>
     */
    com.google.protobuf.ByteString
        getErrInfoBytes();
  }
  /**
   * Protobuf type {@code platform.ApiPushTokenResponse}
   */
  public  static final class ApiPushTokenResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.ApiPushTokenResponse)
      ApiPushTokenResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ApiPushTokenResponse.newBuilder() to construct.
    private ApiPushTokenResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiPushTokenResponse() {
      resCode_ = 0;
      resData_ = "";
      errInfo_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ApiPushTokenResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              resCode_ = input.readInt32();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              resData_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              errInfo_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse.class, com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse.Builder.class);
    }

    public static final int RES_CODE_FIELD_NUMBER = 1;
    private int resCode_;
    /**
     * <code>int32 res_code = 1;</code>
     */
    public int getResCode() {
      return resCode_;
    }

    public static final int RES_DATA_FIELD_NUMBER = 2;
    private volatile java.lang.Object resData_;
    /**
     * <code>string res_data = 2;</code>
     */
    public java.lang.String getResData() {
      java.lang.Object ref = resData_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        resData_ = s;
        return s;
      }
    }
    /**
     * <code>string res_data = 2;</code>
     */
    public com.google.protobuf.ByteString
        getResDataBytes() {
      java.lang.Object ref = resData_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        resData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ERR_INFO_FIELD_NUMBER = 3;
    private volatile java.lang.Object errInfo_;
    /**
     * <code>string err_info = 3;</code>
     */
    public java.lang.String getErrInfo() {
      java.lang.Object ref = errInfo_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errInfo_ = s;
        return s;
      }
    }
    /**
     * <code>string err_info = 3;</code>
     */
    public com.google.protobuf.ByteString
        getErrInfoBytes() {
      java.lang.Object ref = errInfo_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errInfo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (resCode_ != 0) {
        output.writeInt32(1, resCode_);
      }
      if (!getResDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, resData_);
      }
      if (!getErrInfoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, errInfo_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (resCode_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, resCode_);
      }
      if (!getResDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, resData_);
      }
      if (!getErrInfoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, errInfo_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse)) {
        return super.equals(obj);
      }
      com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse other = (com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse) obj;

      boolean result = true;
      result = result && (getResCode()
          == other.getResCode());
      result = result && getResData()
          .equals(other.getResData());
      result = result && getErrInfo()
          .equals(other.getErrInfo());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RES_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getResCode();
      hash = (37 * hash) + RES_DATA_FIELD_NUMBER;
      hash = (53 * hash) + getResData().hashCode();
      hash = (37 * hash) + ERR_INFO_FIELD_NUMBER;
      hash = (53 * hash) + getErrInfo().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.ApiPushTokenResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.ApiPushTokenResponse)
        com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse.class, com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse.Builder.class);
      }

      // Construct using com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        resCode_ = 0;

        resData_ = "";

        errInfo_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.platform.UploadPushToken.internal_static_platform_ApiPushTokenResponse_descriptor;
      }

      public com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse getDefaultInstanceForType() {
        return com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse.getDefaultInstance();
      }

      public com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse build() {
        com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse buildPartial() {
        com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse result = new com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse(this);
        result.resCode_ = resCode_;
        result.resData_ = resData_;
        result.errInfo_ = errInfo_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse) {
          return mergeFrom((com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse other) {
        if (other == com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse.getDefaultInstance()) return this;
        if (other.getResCode() != 0) {
          setResCode(other.getResCode());
        }
        if (!other.getResData().isEmpty()) {
          resData_ = other.resData_;
          onChanged();
        }
        if (!other.getErrInfo().isEmpty()) {
          errInfo_ = other.errInfo_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int resCode_ ;
      /**
       * <code>int32 res_code = 1;</code>
       */
      public int getResCode() {
        return resCode_;
      }
      /**
       * <code>int32 res_code = 1;</code>
       */
      public Builder setResCode(int value) {
        
        resCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 res_code = 1;</code>
       */
      public Builder clearResCode() {
        
        resCode_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object resData_ = "";
      /**
       * <code>string res_data = 2;</code>
       */
      public java.lang.String getResData() {
        java.lang.Object ref = resData_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          resData_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string res_data = 2;</code>
       */
      public com.google.protobuf.ByteString
          getResDataBytes() {
        java.lang.Object ref = resData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          resData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string res_data = 2;</code>
       */
      public Builder setResData(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        resData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string res_data = 2;</code>
       */
      public Builder clearResData() {
        
        resData_ = getDefaultInstance().getResData();
        onChanged();
        return this;
      }
      /**
       * <code>string res_data = 2;</code>
       */
      public Builder setResDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        resData_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object errInfo_ = "";
      /**
       * <code>string err_info = 3;</code>
       */
      public java.lang.String getErrInfo() {
        java.lang.Object ref = errInfo_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errInfo_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string err_info = 3;</code>
       */
      public com.google.protobuf.ByteString
          getErrInfoBytes() {
        java.lang.Object ref = errInfo_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errInfo_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string err_info = 3;</code>
       */
      public Builder setErrInfo(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errInfo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string err_info = 3;</code>
       */
      public Builder clearErrInfo() {
        
        errInfo_ = getDefaultInstance().getErrInfo();
        onChanged();
        return this;
      }
      /**
       * <code>string err_info = 3;</code>
       */
      public Builder setErrInfoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errInfo_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:platform.ApiPushTokenResponse)
    }

    // @@protoc_insertion_point(class_scope:platform.ApiPushTokenResponse)
    private static final com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse();
    }

    public static com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiPushTokenResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiPushTokenResponse>() {
      public ApiPushTokenResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiPushTokenResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiPushTokenResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiPushTokenResponse> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.platform.UploadPushToken.ApiPushTokenResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiPushTokenRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiPushTokenRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_ApiPushTokenResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_ApiPushTokenResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\"platform/api_uploadPushToken.proto\022\010pl" +
      "atform\"s\n\023ApiPushTokenRequest\022\024\n\014user_id" +
      "_pubk\030\001 \001(\t\022\030\n\020user_device_pubk\030\002 \001(\t\022\030\n" +
      "\020user_device_sign\030\003 \001(\t\022\022\n\npush_token\030\004 " +
      "\001(\t\"L\n\024ApiPushTokenResponse\022\020\n\010res_code\030" +
      "\001 \001(\005\022\020\n\010res_data\030\002 \001(\t\022\020\n\010err_info\030\003 \001(" +
      "\t2_\n\013ApiUserInfo\022P\n\017uploadPushToken\022\035.pl" +
      "atform.ApiPushTokenRequest\032\036.platform.Ap" +
      "iPushTokenResponseB*\n\027com.zaly.proto.pla" +
      "tformB\017UploadPushTokenb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_platform_ApiPushTokenRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_platform_ApiPushTokenRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiPushTokenRequest_descriptor,
        new java.lang.String[] { "UserIdPubk", "UserDevicePubk", "UserDeviceSign", "PushToken", });
    internal_static_platform_ApiPushTokenResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_platform_ApiPushTokenResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_ApiPushTokenResponse_descriptor,
        new java.lang.String[] { "ResCode", "ResData", "ErrInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
