// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: platform/api_uploadUserInfo.proto

package com.zaly.proto.platform;

public final class UserInfoProto {
  private UserInfoProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UploadUserInfoRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.UploadUserInfoRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string user_id_prik = 1;</code>
     */
    java.lang.String getUserIdPrik();
    /**
     * <code>string user_id_prik = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPrikBytes();

    /**
     * <code>string user_id_pubk = 2;</code>
     */
    java.lang.String getUserIdPubk();
    /**
     * <code>string user_id_pubk = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();

    /**
     * <code>string user_photo = 3;</code>
     */
    java.lang.String getUserPhoto();
    /**
     * <code>string user_photo = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserPhotoBytes();

    /**
     * <code>string user_name = 4;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>string user_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string user_phone_id = 5;</code>
     */
    java.lang.String getUserPhoneId();
    /**
     * <code>string user_phone_id = 5;</code>
     */
    com.google.protobuf.ByteString
        getUserPhoneIdBytes();

    /**
     * <code>string client_type = 6;</code>
     */
    java.lang.String getClientType();
    /**
     * <code>string client_type = 6;</code>
     */
    com.google.protobuf.ByteString
        getClientTypeBytes();

    /**
     * <code>string rom = 7;</code>
     */
    java.lang.String getRom();
    /**
     * <code>string rom = 7;</code>
     */
    com.google.protobuf.ByteString
        getRomBytes();

    /**
     * <code>string push_token = 8;</code>
     */
    java.lang.String getPushToken();
    /**
     * <code>string push_token = 8;</code>
     */
    com.google.protobuf.ByteString
        getPushTokenBytes();
  }
  /**
   * Protobuf type {@code platform.UploadUserInfoRequest}
   */
  public  static final class UploadUserInfoRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.UploadUserInfoRequest)
      UploadUserInfoRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadUserInfoRequest.newBuilder() to construct.
    private UploadUserInfoRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadUserInfoRequest() {
      userIdPrik_ = "";
      userIdPubk_ = "";
      userPhoto_ = "";
      userName_ = "";
      userPhoneId_ = "";
      clientType_ = "";
      rom_ = "";
      pushToken_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadUserInfoRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPrik_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPubk_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userPhoto_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              userPhoneId_ = s;
              break;
            }
            case 50: {
              java.lang.String s = input.readStringRequireUtf8();

              clientType_ = s;
              break;
            }
            case 58: {
              java.lang.String s = input.readStringRequireUtf8();

              rom_ = s;
              break;
            }
            case 66: {
              java.lang.String s = input.readStringRequireUtf8();

              pushToken_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest.class, com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest.Builder.class);
    }

    public static final int USER_ID_PRIK_FIELD_NUMBER = 1;
    private volatile java.lang.Object userIdPrik_;
    /**
     * <code>string user_id_prik = 1;</code>
     */
    public java.lang.String getUserIdPrik() {
      java.lang.Object ref = userIdPrik_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPrik_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id_prik = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPrikBytes() {
      java.lang.Object ref = userIdPrik_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPrik_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 2;
    private volatile java.lang.Object userIdPubk_;
    /**
     * <code>string user_id_pubk = 2;</code>
     */
    public java.lang.String getUserIdPubk() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPubk_ = s;
        return s;
      }
    }
    /**
     * <code>string user_id_pubk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_PHOTO_FIELD_NUMBER = 3;
    private volatile java.lang.Object userPhoto_;
    /**
     * <code>string user_photo = 3;</code>
     */
    public java.lang.String getUserPhoto() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhoto_ = s;
        return s;
      }
    }
    /**
     * <code>string user_photo = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserPhotoBytes() {
      java.lang.Object ref = userPhoto_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhoto_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object userName_;
    /**
     * <code>string user_name = 4;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>string user_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_PHONE_ID_FIELD_NUMBER = 5;
    private volatile java.lang.Object userPhoneId_;
    /**
     * <code>string user_phone_id = 5;</code>
     */
    public java.lang.String getUserPhoneId() {
      java.lang.Object ref = userPhoneId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhoneId_ = s;
        return s;
      }
    }
    /**
     * <code>string user_phone_id = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUserPhoneIdBytes() {
      java.lang.Object ref = userPhoneId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhoneId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CLIENT_TYPE_FIELD_NUMBER = 6;
    private volatile java.lang.Object clientType_;
    /**
     * <code>string client_type = 6;</code>
     */
    public java.lang.String getClientType() {
      java.lang.Object ref = clientType_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        clientType_ = s;
        return s;
      }
    }
    /**
     * <code>string client_type = 6;</code>
     */
    public com.google.protobuf.ByteString
        getClientTypeBytes() {
      java.lang.Object ref = clientType_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        clientType_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ROM_FIELD_NUMBER = 7;
    private volatile java.lang.Object rom_;
    /**
     * <code>string rom = 7;</code>
     */
    public java.lang.String getRom() {
      java.lang.Object ref = rom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        rom_ = s;
        return s;
      }
    }
    /**
     * <code>string rom = 7;</code>
     */
    public com.google.protobuf.ByteString
        getRomBytes() {
      java.lang.Object ref = rom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUSH_TOKEN_FIELD_NUMBER = 8;
    private volatile java.lang.Object pushToken_;
    /**
     * <code>string push_token = 8;</code>
     */
    public java.lang.String getPushToken() {
      java.lang.Object ref = pushToken_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        pushToken_ = s;
        return s;
      }
    }
    /**
     * <code>string push_token = 8;</code>
     */
    public com.google.protobuf.ByteString
        getPushTokenBytes() {
      java.lang.Object ref = pushToken_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        pushToken_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdPrikBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdPrik_);
      }
      if (!getUserIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userIdPubk_);
      }
      if (!getUserPhotoBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPhoto_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userName_);
      }
      if (!getUserPhoneIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, userPhoneId_);
      }
      if (!getClientTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, clientType_);
      }
      if (!getRomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, rom_);
      }
      if (!getPushTokenBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 8, pushToken_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdPrikBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdPrik_);
      }
      if (!getUserIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userIdPubk_);
      }
      if (!getUserPhotoBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPhoto_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userName_);
      }
      if (!getUserPhoneIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, userPhoneId_);
      }
      if (!getClientTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, clientType_);
      }
      if (!getRomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, rom_);
      }
      if (!getPushTokenBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, pushToken_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest)) {
        return super.equals(obj);
      }
      com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest other = (com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest) obj;

      boolean result = true;
      result = result && getUserIdPrik()
          .equals(other.getUserIdPrik());
      result = result && getUserIdPubk()
          .equals(other.getUserIdPubk());
      result = result && getUserPhoto()
          .equals(other.getUserPhoto());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getUserPhoneId()
          .equals(other.getUserPhoneId());
      result = result && getClientType()
          .equals(other.getClientType());
      result = result && getRom()
          .equals(other.getRom());
      result = result && getPushToken()
          .equals(other.getPushToken());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + USER_ID_PRIK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPrik().hashCode();
      hash = (37 * hash) + USER_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPubk().hashCode();
      hash = (37 * hash) + USER_PHOTO_FIELD_NUMBER;
      hash = (53 * hash) + getUserPhoto().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USER_PHONE_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserPhoneId().hashCode();
      hash = (37 * hash) + CLIENT_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getClientType().hashCode();
      hash = (37 * hash) + ROM_FIELD_NUMBER;
      hash = (53 * hash) + getRom().hashCode();
      hash = (37 * hash) + PUSH_TOKEN_FIELD_NUMBER;
      hash = (53 * hash) + getPushToken().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.UploadUserInfoRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.UploadUserInfoRequest)
        com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest.class, com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest.Builder.class);
      }

      // Construct using com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userIdPrik_ = "";

        userIdPubk_ = "";

        userPhoto_ = "";

        userName_ = "";

        userPhoneId_ = "";

        clientType_ = "";

        rom_ = "";

        pushToken_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoRequest_descriptor;
      }

      public com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest getDefaultInstanceForType() {
        return com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest.getDefaultInstance();
      }

      public com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest build() {
        com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest buildPartial() {
        com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest result = new com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest(this);
        result.userIdPrik_ = userIdPrik_;
        result.userIdPubk_ = userIdPubk_;
        result.userPhoto_ = userPhoto_;
        result.userName_ = userName_;
        result.userPhoneId_ = userPhoneId_;
        result.clientType_ = clientType_;
        result.rom_ = rom_;
        result.pushToken_ = pushToken_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest) {
          return mergeFrom((com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest other) {
        if (other == com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest.getDefaultInstance()) return this;
        if (!other.getUserIdPrik().isEmpty()) {
          userIdPrik_ = other.userIdPrik_;
          onChanged();
        }
        if (!other.getUserIdPubk().isEmpty()) {
          userIdPubk_ = other.userIdPubk_;
          onChanged();
        }
        if (!other.getUserPhoto().isEmpty()) {
          userPhoto_ = other.userPhoto_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserPhoneId().isEmpty()) {
          userPhoneId_ = other.userPhoneId_;
          onChanged();
        }
        if (!other.getClientType().isEmpty()) {
          clientType_ = other.clientType_;
          onChanged();
        }
        if (!other.getRom().isEmpty()) {
          rom_ = other.rom_;
          onChanged();
        }
        if (!other.getPushToken().isEmpty()) {
          pushToken_ = other.pushToken_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userIdPrik_ = "";
      /**
       * <code>string user_id_prik = 1;</code>
       */
      public java.lang.String getUserIdPrik() {
        java.lang.Object ref = userIdPrik_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPrik_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id_prik = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPrikBytes() {
        java.lang.Object ref = userIdPrik_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPrik_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id_prik = 1;</code>
       */
      public Builder setUserIdPrik(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPrik_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id_prik = 1;</code>
       */
      public Builder clearUserIdPrik() {
        
        userIdPrik_ = getDefaultInstance().getUserIdPrik();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id_prik = 1;</code>
       */
      public Builder setUserIdPrikBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPrik_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userIdPubk_ = "";
      /**
       * <code>string user_id_pubk = 2;</code>
       */
      public java.lang.String getUserIdPubk() {
        java.lang.Object ref = userIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_id_pubk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        java.lang.Object ref = userIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_id_pubk = 2;</code>
       */
      public Builder setUserIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_id_pubk = 2;</code>
       */
      public Builder clearUserIdPubk() {
        
        userIdPubk_ = getDefaultInstance().getUserIdPubk();
        onChanged();
        return this;
      }
      /**
       * <code>string user_id_pubk = 2;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPhoto_ = "";
      /**
       * <code>string user_photo = 3;</code>
       */
      public java.lang.String getUserPhoto() {
        java.lang.Object ref = userPhoto_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPhoto_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_photo = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserPhotoBytes() {
        java.lang.Object ref = userPhoto_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPhoto_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_photo = 3;</code>
       */
      public Builder setUserPhoto(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPhoto_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_photo = 3;</code>
       */
      public Builder clearUserPhoto() {
        
        userPhoto_ = getDefaultInstance().getUserPhoto();
        onChanged();
        return this;
      }
      /**
       * <code>string user_photo = 3;</code>
       */
      public Builder setUserPhotoBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPhoto_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>string user_name = 4;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_name = 4;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 4;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>string user_name = 4;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPhoneId_ = "";
      /**
       * <code>string user_phone_id = 5;</code>
       */
      public java.lang.String getUserPhoneId() {
        java.lang.Object ref = userPhoneId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPhoneId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string user_phone_id = 5;</code>
       */
      public com.google.protobuf.ByteString
          getUserPhoneIdBytes() {
        java.lang.Object ref = userPhoneId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPhoneId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string user_phone_id = 5;</code>
       */
      public Builder setUserPhoneId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPhoneId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string user_phone_id = 5;</code>
       */
      public Builder clearUserPhoneId() {
        
        userPhoneId_ = getDefaultInstance().getUserPhoneId();
        onChanged();
        return this;
      }
      /**
       * <code>string user_phone_id = 5;</code>
       */
      public Builder setUserPhoneIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPhoneId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object clientType_ = "";
      /**
       * <code>string client_type = 6;</code>
       */
      public java.lang.String getClientType() {
        java.lang.Object ref = clientType_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          clientType_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string client_type = 6;</code>
       */
      public com.google.protobuf.ByteString
          getClientTypeBytes() {
        java.lang.Object ref = clientType_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          clientType_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string client_type = 6;</code>
       */
      public Builder setClientType(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        clientType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string client_type = 6;</code>
       */
      public Builder clearClientType() {
        
        clientType_ = getDefaultInstance().getClientType();
        onChanged();
        return this;
      }
      /**
       * <code>string client_type = 6;</code>
       */
      public Builder setClientTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        clientType_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object rom_ = "";
      /**
       * <code>string rom = 7;</code>
       */
      public java.lang.String getRom() {
        java.lang.Object ref = rom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string rom = 7;</code>
       */
      public com.google.protobuf.ByteString
          getRomBytes() {
        java.lang.Object ref = rom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string rom = 7;</code>
       */
      public Builder setRom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        rom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string rom = 7;</code>
       */
      public Builder clearRom() {
        
        rom_ = getDefaultInstance().getRom();
        onChanged();
        return this;
      }
      /**
       * <code>string rom = 7;</code>
       */
      public Builder setRomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        rom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object pushToken_ = "";
      /**
       * <code>string push_token = 8;</code>
       */
      public java.lang.String getPushToken() {
        java.lang.Object ref = pushToken_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pushToken_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string push_token = 8;</code>
       */
      public com.google.protobuf.ByteString
          getPushTokenBytes() {
        java.lang.Object ref = pushToken_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pushToken_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string push_token = 8;</code>
       */
      public Builder setPushToken(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pushToken_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string push_token = 8;</code>
       */
      public Builder clearPushToken() {
        
        pushToken_ = getDefaultInstance().getPushToken();
        onChanged();
        return this;
      }
      /**
       * <code>string push_token = 8;</code>
       */
      public Builder setPushTokenBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        pushToken_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:platform.UploadUserInfoRequest)
    }

    // @@protoc_insertion_point(class_scope:platform.UploadUserInfoRequest)
    private static final com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest();
    }

    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadUserInfoRequest>
        PARSER = new com.google.protobuf.AbstractParser<UploadUserInfoRequest>() {
      public UploadUserInfoRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UploadUserInfoRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadUserInfoRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadUserInfoRequest> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.platform.UserInfoProto.UploadUserInfoRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface UploadUserInfoResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:platform.UploadUserInfoResponse)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code platform.UploadUserInfoResponse}
   */
  public  static final class UploadUserInfoResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:platform.UploadUserInfoResponse)
      UploadUserInfoResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use UploadUserInfoResponse.newBuilder() to construct.
    private UploadUserInfoResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private UploadUserInfoResponse() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private UploadUserInfoResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse.class, com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse.Builder.class);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse)) {
        return super.equals(obj);
      }
      com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse other = (com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code platform.UploadUserInfoResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:platform.UploadUserInfoResponse)
        com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse.class, com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse.Builder.class);
      }

      // Construct using com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.platform.UserInfoProto.internal_static_platform_UploadUserInfoResponse_descriptor;
      }

      public com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse getDefaultInstanceForType() {
        return com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse.getDefaultInstance();
      }

      public com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse build() {
        com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse buildPartial() {
        com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse result = new com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse(this);
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse) {
          return mergeFrom((com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse other) {
        if (other == com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:platform.UploadUserInfoResponse)
    }

    // @@protoc_insertion_point(class_scope:platform.UploadUserInfoResponse)
    private static final com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse();
    }

    public static com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<UploadUserInfoResponse>
        PARSER = new com.google.protobuf.AbstractParser<UploadUserInfoResponse>() {
      public UploadUserInfoResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new UploadUserInfoResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<UploadUserInfoResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<UploadUserInfoResponse> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.platform.UserInfoProto.UploadUserInfoResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_UploadUserInfoRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_UploadUserInfoRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_platform_UploadUserInfoResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_platform_UploadUserInfoResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!platform/api_uploadUserInfo.proto\022\010pla" +
      "tform\"\267\001\n\025UploadUserInfoRequest\022\024\n\014user_" +
      "id_prik\030\001 \001(\t\022\024\n\014user_id_pubk\030\002 \001(\t\022\022\n\nu" +
      "ser_photo\030\003 \001(\t\022\021\n\tuser_name\030\004 \001(\t\022\025\n\rus" +
      "er_phone_id\030\005 \001(\t\022\023\n\013client_type\030\006 \001(\t\022\013" +
      "\n\003rom\030\007 \001(\t\022\022\n\npush_token\030\010 \001(\t\"\030\n\026Uploa" +
      "dUserInfoResponse2f\n\017UserInfoService\022S\n\016" +
      "uploadUserInfo\022\037.platform.UploadUserInfo" +
      "Request\032 .platform.UploadUserInfoRespons" +
      "eB(\n\027com.zaly.proto.platformB\rUserInfoPr",
      "otob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_platform_UploadUserInfoRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_platform_UploadUserInfoRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_UploadUserInfoRequest_descriptor,
        new java.lang.String[] { "UserIdPrik", "UserIdPubk", "UserPhoto", "UserName", "UserPhoneId", "ClientType", "Rom", "PushToken", });
    internal_static_platform_UploadUserInfoResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_platform_UploadUserInfoResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_platform_UploadUserInfoResponse_descriptor,
        new java.lang.String[] { });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
