// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: site/api_login.proto

package com.zaly.proto.site;

public final class ImLoginProto {
  private ImLoginProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ApiLoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiLoginRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string user_id_pubk = 1;</code>
     */
    java.lang.String getUserIdPubk();
    /**
     * <code>optional string user_id_pubk = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserIdPubkBytes();

    /**
     * <code>optional string user_device_id_pubk = 2;</code>
     */
    java.lang.String getUserDeviceIdPubk();
    /**
     * <code>optional string user_device_id_pubk = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceIdPubkBytes();

    /**
     * <pre>
     *使用user_device_id_sign验证user_device_id_pubk合法性
     * </pre>
     *
     * <code>optional string user_device_id_sign = 3;</code>
     */
    java.lang.String getUserDeviceIdSign();
    /**
     * <pre>
     *使用user_device_id_sign验证user_device_id_pubk合法性
     * </pre>
     *
     * <code>optional string user_device_id_sign = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceIdSignBytes();

    /**
     * <code>optional string user_device_name = 4;</code>
     */
    java.lang.String getUserDeviceName();
    /**
     * <code>optional string user_device_name = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserDeviceNameBytes();
  }
  /**
   * Protobuf type {@code site.ApiLoginRequest}
   */
  public  static final class ApiLoginRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiLoginRequest)
      ApiLoginRequestOrBuilder {
    // Use ApiLoginRequest.newBuilder() to construct.
    private ApiLoginRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiLoginRequest() {
      userIdPubk_ = "";
      userDeviceIdPubk_ = "";
      userDeviceIdSign_ = "";
      userDeviceName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiLoginRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userIdPubk_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceIdPubk_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceIdSign_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              userDeviceName_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.site.ImLoginProto.ApiLoginRequest.class, com.zaly.proto.site.ImLoginProto.ApiLoginRequest.Builder.class);
    }

    public static final int USER_ID_PUBK_FIELD_NUMBER = 1;
    private volatile java.lang.Object userIdPubk_;
    /**
     * <code>optional string user_id_pubk = 1;</code>
     */
    public java.lang.String getUserIdPubk() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userIdPubk_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_id_pubk = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserIdPubkBytes() {
      java.lang.Object ref = userIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICE_ID_PUBK_FIELD_NUMBER = 2;
    private volatile java.lang.Object userDeviceIdPubk_;
    /**
     * <code>optional string user_device_id_pubk = 2;</code>
     */
    public java.lang.String getUserDeviceIdPubk() {
      java.lang.Object ref = userDeviceIdPubk_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceIdPubk_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_device_id_pubk = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceIdPubkBytes() {
      java.lang.Object ref = userDeviceIdPubk_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceIdPubk_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICE_ID_SIGN_FIELD_NUMBER = 3;
    private volatile java.lang.Object userDeviceIdSign_;
    /**
     * <pre>
     *使用user_device_id_sign验证user_device_id_pubk合法性
     * </pre>
     *
     * <code>optional string user_device_id_sign = 3;</code>
     */
    public java.lang.String getUserDeviceIdSign() {
      java.lang.Object ref = userDeviceIdSign_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceIdSign_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *使用user_device_id_sign验证user_device_id_pubk合法性
     * </pre>
     *
     * <code>optional string user_device_id_sign = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceIdSignBytes() {
      java.lang.Object ref = userDeviceIdSign_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceIdSign_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_DEVICE_NAME_FIELD_NUMBER = 4;
    private volatile java.lang.Object userDeviceName_;
    /**
     * <code>optional string user_device_name = 4;</code>
     */
    public java.lang.String getUserDeviceName() {
      java.lang.Object ref = userDeviceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userDeviceName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_device_name = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserDeviceNameBytes() {
      java.lang.Object ref = userDeviceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userDeviceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userIdPubk_);
      }
      if (!getUserDeviceIdPubkBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userDeviceIdPubk_);
      }
      if (!getUserDeviceIdSignBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userDeviceIdSign_);
      }
      if (!getUserDeviceNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userDeviceName_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userIdPubk_);
      }
      if (!getUserDeviceIdPubkBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userDeviceIdPubk_);
      }
      if (!getUserDeviceIdSignBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userDeviceIdSign_);
      }
      if (!getUserDeviceNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userDeviceName_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.site.ImLoginProto.ApiLoginRequest)) {
        return super.equals(obj);
      }
      com.zaly.proto.site.ImLoginProto.ApiLoginRequest other = (com.zaly.proto.site.ImLoginProto.ApiLoginRequest) obj;

      boolean result = true;
      result = result && getUserIdPubk()
          .equals(other.getUserIdPubk());
      result = result && getUserDeviceIdPubk()
          .equals(other.getUserDeviceIdPubk());
      result = result && getUserDeviceIdSign()
          .equals(other.getUserDeviceIdSign());
      result = result && getUserDeviceName()
          .equals(other.getUserDeviceName());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserIdPubk().hashCode();
      hash = (37 * hash) + USER_DEVICE_ID_PUBK_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceIdPubk().hashCode();
      hash = (37 * hash) + USER_DEVICE_ID_SIGN_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceIdSign().hashCode();
      hash = (37 * hash) + USER_DEVICE_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserDeviceName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.site.ImLoginProto.ApiLoginRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiLoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiLoginRequest)
        com.zaly.proto.site.ImLoginProto.ApiLoginRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.site.ImLoginProto.ApiLoginRequest.class, com.zaly.proto.site.ImLoginProto.ApiLoginRequest.Builder.class);
      }

      // Construct using com.zaly.proto.site.ImLoginProto.ApiLoginRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userIdPubk_ = "";

        userDeviceIdPubk_ = "";

        userDeviceIdSign_ = "";

        userDeviceName_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginRequest_descriptor;
      }

      public com.zaly.proto.site.ImLoginProto.ApiLoginRequest getDefaultInstanceForType() {
        return com.zaly.proto.site.ImLoginProto.ApiLoginRequest.getDefaultInstance();
      }

      public com.zaly.proto.site.ImLoginProto.ApiLoginRequest build() {
        com.zaly.proto.site.ImLoginProto.ApiLoginRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.site.ImLoginProto.ApiLoginRequest buildPartial() {
        com.zaly.proto.site.ImLoginProto.ApiLoginRequest result = new com.zaly.proto.site.ImLoginProto.ApiLoginRequest(this);
        result.userIdPubk_ = userIdPubk_;
        result.userDeviceIdPubk_ = userDeviceIdPubk_;
        result.userDeviceIdSign_ = userDeviceIdSign_;
        result.userDeviceName_ = userDeviceName_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.site.ImLoginProto.ApiLoginRequest) {
          return mergeFrom((com.zaly.proto.site.ImLoginProto.ApiLoginRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.site.ImLoginProto.ApiLoginRequest other) {
        if (other == com.zaly.proto.site.ImLoginProto.ApiLoginRequest.getDefaultInstance()) return this;
        if (!other.getUserIdPubk().isEmpty()) {
          userIdPubk_ = other.userIdPubk_;
          onChanged();
        }
        if (!other.getUserDeviceIdPubk().isEmpty()) {
          userDeviceIdPubk_ = other.userDeviceIdPubk_;
          onChanged();
        }
        if (!other.getUserDeviceIdSign().isEmpty()) {
          userDeviceIdSign_ = other.userDeviceIdSign_;
          onChanged();
        }
        if (!other.getUserDeviceName().isEmpty()) {
          userDeviceName_ = other.userDeviceName_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.site.ImLoginProto.ApiLoginRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.site.ImLoginProto.ApiLoginRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userIdPubk_ = "";
      /**
       * <code>optional string user_id_pubk = 1;</code>
       */
      public java.lang.String getUserIdPubk() {
        java.lang.Object ref = userIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_id_pubk = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserIdPubkBytes() {
        java.lang.Object ref = userIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder clearUserIdPubk() {
        
        userIdPubk_ = getDefaultInstance().getUserIdPubk();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_id_pubk = 1;</code>
       */
      public Builder setUserIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceIdPubk_ = "";
      /**
       * <code>optional string user_device_id_pubk = 2;</code>
       */
      public java.lang.String getUserDeviceIdPubk() {
        java.lang.Object ref = userDeviceIdPubk_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceIdPubk_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_device_id_pubk = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceIdPubkBytes() {
        java.lang.Object ref = userDeviceIdPubk_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceIdPubk_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_device_id_pubk = 2;</code>
       */
      public Builder setUserDeviceIdPubk(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceIdPubk_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_device_id_pubk = 2;</code>
       */
      public Builder clearUserDeviceIdPubk() {
        
        userDeviceIdPubk_ = getDefaultInstance().getUserDeviceIdPubk();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_device_id_pubk = 2;</code>
       */
      public Builder setUserDeviceIdPubkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceIdPubk_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceIdSign_ = "";
      /**
       * <pre>
       *使用user_device_id_sign验证user_device_id_pubk合法性
       * </pre>
       *
       * <code>optional string user_device_id_sign = 3;</code>
       */
      public java.lang.String getUserDeviceIdSign() {
        java.lang.Object ref = userDeviceIdSign_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceIdSign_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *使用user_device_id_sign验证user_device_id_pubk合法性
       * </pre>
       *
       * <code>optional string user_device_id_sign = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceIdSignBytes() {
        java.lang.Object ref = userDeviceIdSign_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceIdSign_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *使用user_device_id_sign验证user_device_id_pubk合法性
       * </pre>
       *
       * <code>optional string user_device_id_sign = 3;</code>
       */
      public Builder setUserDeviceIdSign(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceIdSign_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *使用user_device_id_sign验证user_device_id_pubk合法性
       * </pre>
       *
       * <code>optional string user_device_id_sign = 3;</code>
       */
      public Builder clearUserDeviceIdSign() {
        
        userDeviceIdSign_ = getDefaultInstance().getUserDeviceIdSign();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *使用user_device_id_sign验证user_device_id_pubk合法性
       * </pre>
       *
       * <code>optional string user_device_id_sign = 3;</code>
       */
      public Builder setUserDeviceIdSignBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceIdSign_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userDeviceName_ = "";
      /**
       * <code>optional string user_device_name = 4;</code>
       */
      public java.lang.String getUserDeviceName() {
        java.lang.Object ref = userDeviceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userDeviceName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_device_name = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserDeviceNameBytes() {
        java.lang.Object ref = userDeviceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userDeviceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_device_name = 4;</code>
       */
      public Builder setUserDeviceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userDeviceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_device_name = 4;</code>
       */
      public Builder clearUserDeviceName() {
        
        userDeviceName_ = getDefaultInstance().getUserDeviceName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_device_name = 4;</code>
       */
      public Builder setUserDeviceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userDeviceName_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiLoginRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ApiLoginRequest)
    private static final com.zaly.proto.site.ImLoginProto.ApiLoginRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.site.ImLoginProto.ApiLoginRequest();
    }

    public static com.zaly.proto.site.ImLoginProto.ApiLoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiLoginRequest>
        PARSER = new com.google.protobuf.AbstractParser<ApiLoginRequest>() {
      public ApiLoginRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiLoginRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiLoginRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiLoginRequest> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.site.ImLoginProto.ApiLoginRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ApiLoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ApiLoginResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string user_session_id = 1;</code>
     */
    java.lang.String getUserSessionId();
    /**
     * <code>optional string user_session_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getUserSessionIdBytes();

    /**
     * <code>optional string site_user_id = 2;</code>
     */
    java.lang.String getSiteUserId();
    /**
     * <code>optional string site_user_id = 2;</code>
     */
    com.google.protobuf.ByteString
        getSiteUserIdBytes();
  }
  /**
   * Protobuf type {@code site.ApiLoginResponse}
   */
  public  static final class ApiLoginResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ApiLoginResponse)
      ApiLoginResponseOrBuilder {
    // Use ApiLoginResponse.newBuilder() to construct.
    private ApiLoginResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ApiLoginResponse() {
      userSessionId_ = "";
      siteUserId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ApiLoginResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              userSessionId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              siteUserId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.site.ImLoginProto.ApiLoginResponse.class, com.zaly.proto.site.ImLoginProto.ApiLoginResponse.Builder.class);
    }

    public static final int USER_SESSION_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object userSessionId_;
    /**
     * <code>optional string user_session_id = 1;</code>
     */
    public java.lang.String getUserSessionId() {
      java.lang.Object ref = userSessionId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userSessionId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_session_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUserSessionIdBytes() {
      java.lang.Object ref = userSessionId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userSessionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SITE_USER_ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object siteUserId_;
    /**
     * <code>optional string site_user_id = 2;</code>
     */
    public java.lang.String getSiteUserId() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteUserId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string site_user_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSiteUserIdBytes() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUserSessionIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, userSessionId_);
      }
      if (!getSiteUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, siteUserId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUserSessionIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, userSessionId_);
      }
      if (!getSiteUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, siteUserId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.site.ImLoginProto.ApiLoginResponse)) {
        return super.equals(obj);
      }
      com.zaly.proto.site.ImLoginProto.ApiLoginResponse other = (com.zaly.proto.site.ImLoginProto.ApiLoginResponse) obj;

      boolean result = true;
      result = result && getUserSessionId()
          .equals(other.getUserSessionId());
      result = result && getSiteUserId()
          .equals(other.getSiteUserId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + USER_SESSION_ID_FIELD_NUMBER;
      hash = (53 * hash) + getUserSessionId().hashCode();
      hash = (37 * hash) + SITE_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.site.ImLoginProto.ApiLoginResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ApiLoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ApiLoginResponse)
        com.zaly.proto.site.ImLoginProto.ApiLoginResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.site.ImLoginProto.ApiLoginResponse.class, com.zaly.proto.site.ImLoginProto.ApiLoginResponse.Builder.class);
      }

      // Construct using com.zaly.proto.site.ImLoginProto.ApiLoginResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        userSessionId_ = "";

        siteUserId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.site.ImLoginProto.internal_static_site_ApiLoginResponse_descriptor;
      }

      public com.zaly.proto.site.ImLoginProto.ApiLoginResponse getDefaultInstanceForType() {
        return com.zaly.proto.site.ImLoginProto.ApiLoginResponse.getDefaultInstance();
      }

      public com.zaly.proto.site.ImLoginProto.ApiLoginResponse build() {
        com.zaly.proto.site.ImLoginProto.ApiLoginResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.site.ImLoginProto.ApiLoginResponse buildPartial() {
        com.zaly.proto.site.ImLoginProto.ApiLoginResponse result = new com.zaly.proto.site.ImLoginProto.ApiLoginResponse(this);
        result.userSessionId_ = userSessionId_;
        result.siteUserId_ = siteUserId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.site.ImLoginProto.ApiLoginResponse) {
          return mergeFrom((com.zaly.proto.site.ImLoginProto.ApiLoginResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.site.ImLoginProto.ApiLoginResponse other) {
        if (other == com.zaly.proto.site.ImLoginProto.ApiLoginResponse.getDefaultInstance()) return this;
        if (!other.getUserSessionId().isEmpty()) {
          userSessionId_ = other.userSessionId_;
          onChanged();
        }
        if (!other.getSiteUserId().isEmpty()) {
          siteUserId_ = other.siteUserId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.site.ImLoginProto.ApiLoginResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.site.ImLoginProto.ApiLoginResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object userSessionId_ = "";
      /**
       * <code>optional string user_session_id = 1;</code>
       */
      public java.lang.String getUserSessionId() {
        java.lang.Object ref = userSessionId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userSessionId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_session_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUserSessionIdBytes() {
        java.lang.Object ref = userSessionId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userSessionId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_session_id = 1;</code>
       */
      public Builder setUserSessionId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userSessionId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_session_id = 1;</code>
       */
      public Builder clearUserSessionId() {
        
        userSessionId_ = getDefaultInstance().getUserSessionId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_session_id = 1;</code>
       */
      public Builder setUserSessionIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userSessionId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object siteUserId_ = "";
      /**
       * <code>optional string site_user_id = 2;</code>
       */
      public java.lang.String getSiteUserId() {
        java.lang.Object ref = siteUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string site_user_id = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSiteUserIdBytes() {
        java.lang.Object ref = siteUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string site_user_id = 2;</code>
       */
      public Builder setSiteUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string site_user_id = 2;</code>
       */
      public Builder clearSiteUserId() {
        
        siteUserId_ = getDefaultInstance().getSiteUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string site_user_id = 2;</code>
       */
      public Builder setSiteUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteUserId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.ApiLoginResponse)
    }

    // @@protoc_insertion_point(class_scope:site.ApiLoginResponse)
    private static final com.zaly.proto.site.ImLoginProto.ApiLoginResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.site.ImLoginProto.ApiLoginResponse();
    }

    public static com.zaly.proto.site.ImLoginProto.ApiLoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ApiLoginResponse>
        PARSER = new com.google.protobuf.AbstractParser<ApiLoginResponse>() {
      public ApiLoginResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ApiLoginResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ApiLoginResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ApiLoginResponse> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.site.ImLoginProto.ApiLoginResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiLoginRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiLoginRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ApiLoginResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ApiLoginResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024site/api_login.proto\022\004site\"{\n\017ApiLogin" +
      "Request\022\024\n\014user_id_pubk\030\001 \001(\t\022\033\n\023user_de" +
      "vice_id_pubk\030\002 \001(\t\022\033\n\023user_device_id_sig" +
      "n\030\003 \001(\t\022\030\n\020user_device_name\030\004 \001(\t\"A\n\020Api" +
      "LoginResponse\022\027\n\017user_session_id\030\001 \001(\t\022\024" +
      "\n\014site_user_id\030\002 \001(\t2B\n\010ApiLogin\0226\n\005logi" +
      "n\022\025.site.ApiLoginRequest\032\026.site.ApiLogin" +
      "ResponseB#\n\023com.zaly.proto.siteB\014ImLogin" +
      "Protob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_site_ApiLoginRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ApiLoginRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiLoginRequest_descriptor,
        new java.lang.String[] { "UserIdPubk", "UserDeviceIdPubk", "UserDeviceIdSign", "UserDeviceName", });
    internal_static_site_ApiLoginResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_ApiLoginResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ApiLoginResponse_descriptor,
        new java.lang.String[] { "UserSessionId", "SiteUserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
