// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: site/im_toSiteMsg.proto

package com.zaly.proto.site;

public final class ImToSiteMsgProto {
  private ImToSiteMsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ToSiteMsgRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.ToSiteMsgRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.core.MsgType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <code>.core.MsgType type = 1;</code>
     */
    com.zaly.proto.core.CoreProto.MsgType getType();

    /**
     * <code>.core.MsgText text = 2;</code>
     */
    boolean hasText();
    /**
     * <code>.core.MsgText text = 2;</code>
     */
    com.zaly.proto.core.CoreProto.MsgText getText();
    /**
     * <code>.core.MsgText text = 2;</code>
     */
    com.zaly.proto.core.CoreProto.MsgTextOrBuilder getTextOrBuilder();

    /**
     * <code>.core.MsgSecretText secretText = 3;</code>
     */
    boolean hasSecretText();
    /**
     * <code>.core.MsgSecretText secretText = 3;</code>
     */
    com.zaly.proto.core.CoreProto.MsgSecretText getSecretText();
    /**
     * <code>.core.MsgSecretText secretText = 3;</code>
     */
    com.zaly.proto.core.CoreProto.MsgSecretTextOrBuilder getSecretTextOrBuilder();

    /**
     * <code>.core.GroupText groupText = 4;</code>
     */
    boolean hasGroupText();
    /**
     * <code>.core.GroupText groupText = 4;</code>
     */
    com.zaly.proto.core.CoreProto.GroupText getGroupText();
    /**
     * <code>.core.GroupText groupText = 4;</code>
     */
    com.zaly.proto.core.CoreProto.GroupTextOrBuilder getGroupTextOrBuilder();

    /**
     * <code>.core.GroupSecretText groupSecretText = 5;</code>
     */
    boolean hasGroupSecretText();
    /**
     * <code>.core.GroupSecretText groupSecretText = 5;</code>
     */
    com.zaly.proto.core.CoreProto.GroupSecretText getGroupSecretText();
    /**
     * <code>.core.GroupSecretText groupSecretText = 5;</code>
     */
    com.zaly.proto.core.CoreProto.GroupSecretTextOrBuilder getGroupSecretTextOrBuilder();
  }
  /**
   * Protobuf type {@code site.ToSiteMsgRequest}
   */
  public  static final class ToSiteMsgRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.ToSiteMsgRequest)
      ToSiteMsgRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ToSiteMsgRequest.newBuilder() to construct.
    private ToSiteMsgRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ToSiteMsgRequest() {
      type_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ToSiteMsgRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {
              com.zaly.proto.core.CoreProto.MsgText.Builder subBuilder = null;
              if (text_ != null) {
                subBuilder = text_.toBuilder();
              }
              text_ = input.readMessage(com.zaly.proto.core.CoreProto.MsgText.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(text_);
                text_ = subBuilder.buildPartial();
              }

              break;
            }
            case 26: {
              com.zaly.proto.core.CoreProto.MsgSecretText.Builder subBuilder = null;
              if (secretText_ != null) {
                subBuilder = secretText_.toBuilder();
              }
              secretText_ = input.readMessage(com.zaly.proto.core.CoreProto.MsgSecretText.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(secretText_);
                secretText_ = subBuilder.buildPartial();
              }

              break;
            }
            case 34: {
              com.zaly.proto.core.CoreProto.GroupText.Builder subBuilder = null;
              if (groupText_ != null) {
                subBuilder = groupText_.toBuilder();
              }
              groupText_ = input.readMessage(com.zaly.proto.core.CoreProto.GroupText.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(groupText_);
                groupText_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.zaly.proto.core.CoreProto.GroupSecretText.Builder subBuilder = null;
              if (groupSecretText_ != null) {
                subBuilder = groupSecretText_.toBuilder();
              }
              groupSecretText_ = input.readMessage(com.zaly.proto.core.CoreProto.GroupSecretText.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(groupSecretText_);
                groupSecretText_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.site.ImToSiteMsgProto.internal_static_site_ToSiteMsgRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.site.ImToSiteMsgProto.internal_static_site_ToSiteMsgRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest.class, com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest.Builder.class);
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <code>.core.MsgType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>.core.MsgType type = 1;</code>
     */
    public com.zaly.proto.core.CoreProto.MsgType getType() {
      com.zaly.proto.core.CoreProto.MsgType result = com.zaly.proto.core.CoreProto.MsgType.valueOf(type_);
      return result == null ? com.zaly.proto.core.CoreProto.MsgType.UNRECOGNIZED : result;
    }

    public static final int TEXT_FIELD_NUMBER = 2;
    private com.zaly.proto.core.CoreProto.MsgText text_;
    /**
     * <code>.core.MsgText text = 2;</code>
     */
    public boolean hasText() {
      return text_ != null;
    }
    /**
     * <code>.core.MsgText text = 2;</code>
     */
    public com.zaly.proto.core.CoreProto.MsgText getText() {
      return text_ == null ? com.zaly.proto.core.CoreProto.MsgText.getDefaultInstance() : text_;
    }
    /**
     * <code>.core.MsgText text = 2;</code>
     */
    public com.zaly.proto.core.CoreProto.MsgTextOrBuilder getTextOrBuilder() {
      return getText();
    }

    public static final int SECRETTEXT_FIELD_NUMBER = 3;
    private com.zaly.proto.core.CoreProto.MsgSecretText secretText_;
    /**
     * <code>.core.MsgSecretText secretText = 3;</code>
     */
    public boolean hasSecretText() {
      return secretText_ != null;
    }
    /**
     * <code>.core.MsgSecretText secretText = 3;</code>
     */
    public com.zaly.proto.core.CoreProto.MsgSecretText getSecretText() {
      return secretText_ == null ? com.zaly.proto.core.CoreProto.MsgSecretText.getDefaultInstance() : secretText_;
    }
    /**
     * <code>.core.MsgSecretText secretText = 3;</code>
     */
    public com.zaly.proto.core.CoreProto.MsgSecretTextOrBuilder getSecretTextOrBuilder() {
      return getSecretText();
    }

    public static final int GROUPTEXT_FIELD_NUMBER = 4;
    private com.zaly.proto.core.CoreProto.GroupText groupText_;
    /**
     * <code>.core.GroupText groupText = 4;</code>
     */
    public boolean hasGroupText() {
      return groupText_ != null;
    }
    /**
     * <code>.core.GroupText groupText = 4;</code>
     */
    public com.zaly.proto.core.CoreProto.GroupText getGroupText() {
      return groupText_ == null ? com.zaly.proto.core.CoreProto.GroupText.getDefaultInstance() : groupText_;
    }
    /**
     * <code>.core.GroupText groupText = 4;</code>
     */
    public com.zaly.proto.core.CoreProto.GroupTextOrBuilder getGroupTextOrBuilder() {
      return getGroupText();
    }

    public static final int GROUPSECRETTEXT_FIELD_NUMBER = 5;
    private com.zaly.proto.core.CoreProto.GroupSecretText groupSecretText_;
    /**
     * <code>.core.GroupSecretText groupSecretText = 5;</code>
     */
    public boolean hasGroupSecretText() {
      return groupSecretText_ != null;
    }
    /**
     * <code>.core.GroupSecretText groupSecretText = 5;</code>
     */
    public com.zaly.proto.core.CoreProto.GroupSecretText getGroupSecretText() {
      return groupSecretText_ == null ? com.zaly.proto.core.CoreProto.GroupSecretText.getDefaultInstance() : groupSecretText_;
    }
    /**
     * <code>.core.GroupSecretText groupSecretText = 5;</code>
     */
    public com.zaly.proto.core.CoreProto.GroupSecretTextOrBuilder getGroupSecretTextOrBuilder() {
      return getGroupSecretText();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != com.zaly.proto.core.CoreProto.MsgType.NOTICE.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (text_ != null) {
        output.writeMessage(2, getText());
      }
      if (secretText_ != null) {
        output.writeMessage(3, getSecretText());
      }
      if (groupText_ != null) {
        output.writeMessage(4, getGroupText());
      }
      if (groupSecretText_ != null) {
        output.writeMessage(5, getGroupSecretText());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != com.zaly.proto.core.CoreProto.MsgType.NOTICE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (text_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getText());
      }
      if (secretText_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getSecretText());
      }
      if (groupText_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getGroupText());
      }
      if (groupSecretText_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getGroupSecretText());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest)) {
        return super.equals(obj);
      }
      com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest other = (com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && (hasText() == other.hasText());
      if (hasText()) {
        result = result && getText()
            .equals(other.getText());
      }
      result = result && (hasSecretText() == other.hasSecretText());
      if (hasSecretText()) {
        result = result && getSecretText()
            .equals(other.getSecretText());
      }
      result = result && (hasGroupText() == other.hasGroupText());
      if (hasGroupText()) {
        result = result && getGroupText()
            .equals(other.getGroupText());
      }
      result = result && (hasGroupSecretText() == other.hasGroupSecretText());
      if (hasGroupSecretText()) {
        result = result && getGroupSecretText()
            .equals(other.getGroupSecretText());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      if (hasText()) {
        hash = (37 * hash) + TEXT_FIELD_NUMBER;
        hash = (53 * hash) + getText().hashCode();
      }
      if (hasSecretText()) {
        hash = (37 * hash) + SECRETTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getSecretText().hashCode();
      }
      if (hasGroupText()) {
        hash = (37 * hash) + GROUPTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getGroupText().hashCode();
      }
      if (hasGroupSecretText()) {
        hash = (37 * hash) + GROUPSECRETTEXT_FIELD_NUMBER;
        hash = (53 * hash) + getGroupSecretText().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.ToSiteMsgRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.ToSiteMsgRequest)
        com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.site.ImToSiteMsgProto.internal_static_site_ToSiteMsgRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.site.ImToSiteMsgProto.internal_static_site_ToSiteMsgRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest.class, com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest.Builder.class);
      }

      // Construct using com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        if (textBuilder_ == null) {
          text_ = null;
        } else {
          text_ = null;
          textBuilder_ = null;
        }
        if (secretTextBuilder_ == null) {
          secretText_ = null;
        } else {
          secretText_ = null;
          secretTextBuilder_ = null;
        }
        if (groupTextBuilder_ == null) {
          groupText_ = null;
        } else {
          groupText_ = null;
          groupTextBuilder_ = null;
        }
        if (groupSecretTextBuilder_ == null) {
          groupSecretText_ = null;
        } else {
          groupSecretText_ = null;
          groupSecretTextBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.site.ImToSiteMsgProto.internal_static_site_ToSiteMsgRequest_descriptor;
      }

      public com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest getDefaultInstanceForType() {
        return com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest.getDefaultInstance();
      }

      public com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest build() {
        com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest buildPartial() {
        com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest result = new com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest(this);
        result.type_ = type_;
        if (textBuilder_ == null) {
          result.text_ = text_;
        } else {
          result.text_ = textBuilder_.build();
        }
        if (secretTextBuilder_ == null) {
          result.secretText_ = secretText_;
        } else {
          result.secretText_ = secretTextBuilder_.build();
        }
        if (groupTextBuilder_ == null) {
          result.groupText_ = groupText_;
        } else {
          result.groupText_ = groupTextBuilder_.build();
        }
        if (groupSecretTextBuilder_ == null) {
          result.groupSecretText_ = groupSecretText_;
        } else {
          result.groupSecretText_ = groupSecretTextBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest) {
          return mergeFrom((com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest other) {
        if (other == com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.hasText()) {
          mergeText(other.getText());
        }
        if (other.hasSecretText()) {
          mergeSecretText(other.getSecretText());
        }
        if (other.hasGroupText()) {
          mergeGroupText(other.getGroupText());
        }
        if (other.hasGroupSecretText()) {
          mergeGroupSecretText(other.getGroupSecretText());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <code>.core.MsgType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <code>.core.MsgType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.core.MsgType type = 1;</code>
       */
      public com.zaly.proto.core.CoreProto.MsgType getType() {
        com.zaly.proto.core.CoreProto.MsgType result = com.zaly.proto.core.CoreProto.MsgType.valueOf(type_);
        return result == null ? com.zaly.proto.core.CoreProto.MsgType.UNRECOGNIZED : result;
      }
      /**
       * <code>.core.MsgType type = 1;</code>
       */
      public Builder setType(com.zaly.proto.core.CoreProto.MsgType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.core.MsgType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.zaly.proto.core.CoreProto.MsgText text_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zaly.proto.core.CoreProto.MsgText, com.zaly.proto.core.CoreProto.MsgText.Builder, com.zaly.proto.core.CoreProto.MsgTextOrBuilder> textBuilder_;
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      public boolean hasText() {
        return textBuilder_ != null || text_ != null;
      }
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      public com.zaly.proto.core.CoreProto.MsgText getText() {
        if (textBuilder_ == null) {
          return text_ == null ? com.zaly.proto.core.CoreProto.MsgText.getDefaultInstance() : text_;
        } else {
          return textBuilder_.getMessage();
        }
      }
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      public Builder setText(com.zaly.proto.core.CoreProto.MsgText value) {
        if (textBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          text_ = value;
          onChanged();
        } else {
          textBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      public Builder setText(
          com.zaly.proto.core.CoreProto.MsgText.Builder builderForValue) {
        if (textBuilder_ == null) {
          text_ = builderForValue.build();
          onChanged();
        } else {
          textBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      public Builder mergeText(com.zaly.proto.core.CoreProto.MsgText value) {
        if (textBuilder_ == null) {
          if (text_ != null) {
            text_ =
              com.zaly.proto.core.CoreProto.MsgText.newBuilder(text_).mergeFrom(value).buildPartial();
          } else {
            text_ = value;
          }
          onChanged();
        } else {
          textBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      public Builder clearText() {
        if (textBuilder_ == null) {
          text_ = null;
          onChanged();
        } else {
          text_ = null;
          textBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      public com.zaly.proto.core.CoreProto.MsgText.Builder getTextBuilder() {
        
        onChanged();
        return getTextFieldBuilder().getBuilder();
      }
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      public com.zaly.proto.core.CoreProto.MsgTextOrBuilder getTextOrBuilder() {
        if (textBuilder_ != null) {
          return textBuilder_.getMessageOrBuilder();
        } else {
          return text_ == null ?
              com.zaly.proto.core.CoreProto.MsgText.getDefaultInstance() : text_;
        }
      }
      /**
       * <code>.core.MsgText text = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zaly.proto.core.CoreProto.MsgText, com.zaly.proto.core.CoreProto.MsgText.Builder, com.zaly.proto.core.CoreProto.MsgTextOrBuilder> 
          getTextFieldBuilder() {
        if (textBuilder_ == null) {
          textBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zaly.proto.core.CoreProto.MsgText, com.zaly.proto.core.CoreProto.MsgText.Builder, com.zaly.proto.core.CoreProto.MsgTextOrBuilder>(
                  getText(),
                  getParentForChildren(),
                  isClean());
          text_ = null;
        }
        return textBuilder_;
      }

      private com.zaly.proto.core.CoreProto.MsgSecretText secretText_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zaly.proto.core.CoreProto.MsgSecretText, com.zaly.proto.core.CoreProto.MsgSecretText.Builder, com.zaly.proto.core.CoreProto.MsgSecretTextOrBuilder> secretTextBuilder_;
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      public boolean hasSecretText() {
        return secretTextBuilder_ != null || secretText_ != null;
      }
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      public com.zaly.proto.core.CoreProto.MsgSecretText getSecretText() {
        if (secretTextBuilder_ == null) {
          return secretText_ == null ? com.zaly.proto.core.CoreProto.MsgSecretText.getDefaultInstance() : secretText_;
        } else {
          return secretTextBuilder_.getMessage();
        }
      }
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      public Builder setSecretText(com.zaly.proto.core.CoreProto.MsgSecretText value) {
        if (secretTextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          secretText_ = value;
          onChanged();
        } else {
          secretTextBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      public Builder setSecretText(
          com.zaly.proto.core.CoreProto.MsgSecretText.Builder builderForValue) {
        if (secretTextBuilder_ == null) {
          secretText_ = builderForValue.build();
          onChanged();
        } else {
          secretTextBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      public Builder mergeSecretText(com.zaly.proto.core.CoreProto.MsgSecretText value) {
        if (secretTextBuilder_ == null) {
          if (secretText_ != null) {
            secretText_ =
              com.zaly.proto.core.CoreProto.MsgSecretText.newBuilder(secretText_).mergeFrom(value).buildPartial();
          } else {
            secretText_ = value;
          }
          onChanged();
        } else {
          secretTextBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      public Builder clearSecretText() {
        if (secretTextBuilder_ == null) {
          secretText_ = null;
          onChanged();
        } else {
          secretText_ = null;
          secretTextBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      public com.zaly.proto.core.CoreProto.MsgSecretText.Builder getSecretTextBuilder() {
        
        onChanged();
        return getSecretTextFieldBuilder().getBuilder();
      }
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      public com.zaly.proto.core.CoreProto.MsgSecretTextOrBuilder getSecretTextOrBuilder() {
        if (secretTextBuilder_ != null) {
          return secretTextBuilder_.getMessageOrBuilder();
        } else {
          return secretText_ == null ?
              com.zaly.proto.core.CoreProto.MsgSecretText.getDefaultInstance() : secretText_;
        }
      }
      /**
       * <code>.core.MsgSecretText secretText = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zaly.proto.core.CoreProto.MsgSecretText, com.zaly.proto.core.CoreProto.MsgSecretText.Builder, com.zaly.proto.core.CoreProto.MsgSecretTextOrBuilder> 
          getSecretTextFieldBuilder() {
        if (secretTextBuilder_ == null) {
          secretTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zaly.proto.core.CoreProto.MsgSecretText, com.zaly.proto.core.CoreProto.MsgSecretText.Builder, com.zaly.proto.core.CoreProto.MsgSecretTextOrBuilder>(
                  getSecretText(),
                  getParentForChildren(),
                  isClean());
          secretText_ = null;
        }
        return secretTextBuilder_;
      }

      private com.zaly.proto.core.CoreProto.GroupText groupText_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zaly.proto.core.CoreProto.GroupText, com.zaly.proto.core.CoreProto.GroupText.Builder, com.zaly.proto.core.CoreProto.GroupTextOrBuilder> groupTextBuilder_;
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      public boolean hasGroupText() {
        return groupTextBuilder_ != null || groupText_ != null;
      }
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      public com.zaly.proto.core.CoreProto.GroupText getGroupText() {
        if (groupTextBuilder_ == null) {
          return groupText_ == null ? com.zaly.proto.core.CoreProto.GroupText.getDefaultInstance() : groupText_;
        } else {
          return groupTextBuilder_.getMessage();
        }
      }
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      public Builder setGroupText(com.zaly.proto.core.CoreProto.GroupText value) {
        if (groupTextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          groupText_ = value;
          onChanged();
        } else {
          groupTextBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      public Builder setGroupText(
          com.zaly.proto.core.CoreProto.GroupText.Builder builderForValue) {
        if (groupTextBuilder_ == null) {
          groupText_ = builderForValue.build();
          onChanged();
        } else {
          groupTextBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      public Builder mergeGroupText(com.zaly.proto.core.CoreProto.GroupText value) {
        if (groupTextBuilder_ == null) {
          if (groupText_ != null) {
            groupText_ =
              com.zaly.proto.core.CoreProto.GroupText.newBuilder(groupText_).mergeFrom(value).buildPartial();
          } else {
            groupText_ = value;
          }
          onChanged();
        } else {
          groupTextBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      public Builder clearGroupText() {
        if (groupTextBuilder_ == null) {
          groupText_ = null;
          onChanged();
        } else {
          groupText_ = null;
          groupTextBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      public com.zaly.proto.core.CoreProto.GroupText.Builder getGroupTextBuilder() {
        
        onChanged();
        return getGroupTextFieldBuilder().getBuilder();
      }
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      public com.zaly.proto.core.CoreProto.GroupTextOrBuilder getGroupTextOrBuilder() {
        if (groupTextBuilder_ != null) {
          return groupTextBuilder_.getMessageOrBuilder();
        } else {
          return groupText_ == null ?
              com.zaly.proto.core.CoreProto.GroupText.getDefaultInstance() : groupText_;
        }
      }
      /**
       * <code>.core.GroupText groupText = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zaly.proto.core.CoreProto.GroupText, com.zaly.proto.core.CoreProto.GroupText.Builder, com.zaly.proto.core.CoreProto.GroupTextOrBuilder> 
          getGroupTextFieldBuilder() {
        if (groupTextBuilder_ == null) {
          groupTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zaly.proto.core.CoreProto.GroupText, com.zaly.proto.core.CoreProto.GroupText.Builder, com.zaly.proto.core.CoreProto.GroupTextOrBuilder>(
                  getGroupText(),
                  getParentForChildren(),
                  isClean());
          groupText_ = null;
        }
        return groupTextBuilder_;
      }

      private com.zaly.proto.core.CoreProto.GroupSecretText groupSecretText_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zaly.proto.core.CoreProto.GroupSecretText, com.zaly.proto.core.CoreProto.GroupSecretText.Builder, com.zaly.proto.core.CoreProto.GroupSecretTextOrBuilder> groupSecretTextBuilder_;
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      public boolean hasGroupSecretText() {
        return groupSecretTextBuilder_ != null || groupSecretText_ != null;
      }
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      public com.zaly.proto.core.CoreProto.GroupSecretText getGroupSecretText() {
        if (groupSecretTextBuilder_ == null) {
          return groupSecretText_ == null ? com.zaly.proto.core.CoreProto.GroupSecretText.getDefaultInstance() : groupSecretText_;
        } else {
          return groupSecretTextBuilder_.getMessage();
        }
      }
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      public Builder setGroupSecretText(com.zaly.proto.core.CoreProto.GroupSecretText value) {
        if (groupSecretTextBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          groupSecretText_ = value;
          onChanged();
        } else {
          groupSecretTextBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      public Builder setGroupSecretText(
          com.zaly.proto.core.CoreProto.GroupSecretText.Builder builderForValue) {
        if (groupSecretTextBuilder_ == null) {
          groupSecretText_ = builderForValue.build();
          onChanged();
        } else {
          groupSecretTextBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      public Builder mergeGroupSecretText(com.zaly.proto.core.CoreProto.GroupSecretText value) {
        if (groupSecretTextBuilder_ == null) {
          if (groupSecretText_ != null) {
            groupSecretText_ =
              com.zaly.proto.core.CoreProto.GroupSecretText.newBuilder(groupSecretText_).mergeFrom(value).buildPartial();
          } else {
            groupSecretText_ = value;
          }
          onChanged();
        } else {
          groupSecretTextBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      public Builder clearGroupSecretText() {
        if (groupSecretTextBuilder_ == null) {
          groupSecretText_ = null;
          onChanged();
        } else {
          groupSecretText_ = null;
          groupSecretTextBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      public com.zaly.proto.core.CoreProto.GroupSecretText.Builder getGroupSecretTextBuilder() {
        
        onChanged();
        return getGroupSecretTextFieldBuilder().getBuilder();
      }
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      public com.zaly.proto.core.CoreProto.GroupSecretTextOrBuilder getGroupSecretTextOrBuilder() {
        if (groupSecretTextBuilder_ != null) {
          return groupSecretTextBuilder_.getMessageOrBuilder();
        } else {
          return groupSecretText_ == null ?
              com.zaly.proto.core.CoreProto.GroupSecretText.getDefaultInstance() : groupSecretText_;
        }
      }
      /**
       * <code>.core.GroupSecretText groupSecretText = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.zaly.proto.core.CoreProto.GroupSecretText, com.zaly.proto.core.CoreProto.GroupSecretText.Builder, com.zaly.proto.core.CoreProto.GroupSecretTextOrBuilder> 
          getGroupSecretTextFieldBuilder() {
        if (groupSecretTextBuilder_ == null) {
          groupSecretTextBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.zaly.proto.core.CoreProto.GroupSecretText, com.zaly.proto.core.CoreProto.GroupSecretText.Builder, com.zaly.proto.core.CoreProto.GroupSecretTextOrBuilder>(
                  getGroupSecretText(),
                  getParentForChildren(),
                  isClean());
          groupSecretText_ = null;
        }
        return groupSecretTextBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:site.ToSiteMsgRequest)
    }

    // @@protoc_insertion_point(class_scope:site.ToSiteMsgRequest)
    private static final com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest();
    }

    public static com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ToSiteMsgRequest>
        PARSER = new com.google.protobuf.AbstractParser<ToSiteMsgRequest>() {
      public ToSiteMsgRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ToSiteMsgRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ToSiteMsgRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ToSiteMsgRequest> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.site.ImToSiteMsgProto.ToSiteMsgRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_ToSiteMsgRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_ToSiteMsgRequest_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027site/im_toSiteMsg.proto\022\004site\032\017core/co" +
      "re.proto\"\311\001\n\020ToSiteMsgRequest\022\033\n\004type\030\001 " +
      "\001(\0162\r.core.MsgType\022\033\n\004text\030\002 \001(\0132\r.core." +
      "MsgText\022\'\n\nsecretText\030\003 \001(\0132\023.core.MsgSe" +
      "cretText\022\"\n\tgroupText\030\004 \001(\0132\017.core.Group" +
      "Text\022.\n\017groupSecretText\030\005 \001(\0132\025.core.Gro" +
      "upSecretText2M\n\022ImToSiteMsgService\0227\n\tto" +
      "SiteMsg\022\026.site.ToSiteMsgRequest\032\022.core.N" +
      "oneResponseB\'\n\023com.zaly.proto.siteB\020ImTo" +
      "SiteMsgProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.zaly.proto.core.CoreProto.getDescriptor(),
        }, assigner);
    internal_static_site_ToSiteMsgRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_ToSiteMsgRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_ToSiteMsgRequest_descriptor,
        new java.lang.String[] { "Type", "Text", "SecretText", "GroupText", "GroupSecretText", });
    com.zaly.proto.core.CoreProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
