// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: site/api_getFriendList.proto

package com.zaly.proto.site;

public final class UserFriendProto {
  private UserFriendProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface GetFriendListRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.GetFriendListRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *int32 page =3;
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    java.lang.String getSiteUserId();
    /**
     * <pre>
     *int32 page =3;
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteUserIdBytes();
  }
  /**
   * Protobuf type {@code site.GetFriendListRequest}
   */
  public  static final class GetFriendListRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.GetFriendListRequest)
      GetFriendListRequestOrBuilder {
    // Use GetFriendListRequest.newBuilder() to construct.
    private GetFriendListRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetFriendListRequest() {
      siteUserId_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetFriendListRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              siteUserId_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.site.UserFriendProto.GetFriendListRequest.class, com.zaly.proto.site.UserFriendProto.GetFriendListRequest.Builder.class);
    }

    public static final int SITE_USER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object siteUserId_;
    /**
     * <pre>
     *int32 page =3;
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    public java.lang.String getSiteUserId() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteUserId_ = s;
        return s;
      }
    }
    /**
     * <pre>
     *int32 page =3;
     * </pre>
     *
     * <code>optional string site_user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteUserIdBytes() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSiteUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, siteUserId_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSiteUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, siteUserId_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.site.UserFriendProto.GetFriendListRequest)) {
        return super.equals(obj);
      }
      com.zaly.proto.site.UserFriendProto.GetFriendListRequest other = (com.zaly.proto.site.UserFriendProto.GetFriendListRequest) obj;

      boolean result = true;
      result = result && getSiteUserId()
          .equals(other.getSiteUserId());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SITE_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteUserId().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.site.UserFriendProto.GetFriendListRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.GetFriendListRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.GetFriendListRequest)
        com.zaly.proto.site.UserFriendProto.GetFriendListRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListRequest_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.site.UserFriendProto.GetFriendListRequest.class, com.zaly.proto.site.UserFriendProto.GetFriendListRequest.Builder.class);
      }

      // Construct using com.zaly.proto.site.UserFriendProto.GetFriendListRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        siteUserId_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListRequest_descriptor;
      }

      public com.zaly.proto.site.UserFriendProto.GetFriendListRequest getDefaultInstanceForType() {
        return com.zaly.proto.site.UserFriendProto.GetFriendListRequest.getDefaultInstance();
      }

      public com.zaly.proto.site.UserFriendProto.GetFriendListRequest build() {
        com.zaly.proto.site.UserFriendProto.GetFriendListRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.site.UserFriendProto.GetFriendListRequest buildPartial() {
        com.zaly.proto.site.UserFriendProto.GetFriendListRequest result = new com.zaly.proto.site.UserFriendProto.GetFriendListRequest(this);
        result.siteUserId_ = siteUserId_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.site.UserFriendProto.GetFriendListRequest) {
          return mergeFrom((com.zaly.proto.site.UserFriendProto.GetFriendListRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.site.UserFriendProto.GetFriendListRequest other) {
        if (other == com.zaly.proto.site.UserFriendProto.GetFriendListRequest.getDefaultInstance()) return this;
        if (!other.getSiteUserId().isEmpty()) {
          siteUserId_ = other.siteUserId_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.site.UserFriendProto.GetFriendListRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.site.UserFriendProto.GetFriendListRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object siteUserId_ = "";
      /**
       * <pre>
       *int32 page =3;
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public java.lang.String getSiteUserId() {
        java.lang.Object ref = siteUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       *int32 page =3;
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteUserIdBytes() {
        java.lang.Object ref = siteUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       *int32 page =3;
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder setSiteUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int32 page =3;
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder clearSiteUserId() {
        
        siteUserId_ = getDefaultInstance().getSiteUserId();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *int32 page =3;
       * </pre>
       *
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder setSiteUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteUserId_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.GetFriendListRequest)
    }

    // @@protoc_insertion_point(class_scope:site.GetFriendListRequest)
    private static final com.zaly.proto.site.UserFriendProto.GetFriendListRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.site.UserFriendProto.GetFriendListRequest();
    }

    public static com.zaly.proto.site.UserFriendProto.GetFriendListRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetFriendListRequest>
        PARSER = new com.google.protobuf.AbstractParser<GetFriendListRequest>() {
      public GetFriendListRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetFriendListRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetFriendListRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFriendListRequest> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.site.UserFriendProto.GetFriendListRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface FriendSimpleProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.FriendSimpleProfile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional string site_user_id = 1;</code>
     */
    java.lang.String getSiteUserId();
    /**
     * <code>optional string site_user_id = 1;</code>
     */
    com.google.protobuf.ByteString
        getSiteUserIdBytes();

    /**
     * <code>optional string user_name = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>optional string user_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional string user_photo_url = 3;</code>
     */
    java.lang.String getUserPhotoUrl();
    /**
     * <code>optional string user_photo_url = 3;</code>
     */
    com.google.protobuf.ByteString
        getUserPhotoUrlBytes();
  }
  /**
   * Protobuf type {@code site.FriendSimpleProfile}
   */
  public  static final class FriendSimpleProfile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.FriendSimpleProfile)
      FriendSimpleProfileOrBuilder {
    // Use FriendSimpleProfile.newBuilder() to construct.
    private FriendSimpleProfile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private FriendSimpleProfile() {
      siteUserId_ = "";
      userName_ = "";
      userPhotoUrl_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private FriendSimpleProfile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              siteUserId_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              userName_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              userPhotoUrl_ = s;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.site.UserFriendProto.internal_static_site_FriendSimpleProfile_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.site.UserFriendProto.internal_static_site_FriendSimpleProfile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.class, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder.class);
    }

    public static final int SITE_USER_ID_FIELD_NUMBER = 1;
    private volatile java.lang.Object siteUserId_;
    /**
     * <code>optional string site_user_id = 1;</code>
     */
    public java.lang.String getSiteUserId() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        siteUserId_ = s;
        return s;
      }
    }
    /**
     * <code>optional string site_user_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSiteUserIdBytes() {
      java.lang.Object ref = siteUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        siteUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>optional string user_name = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userName_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_PHOTO_URL_FIELD_NUMBER = 3;
    private volatile java.lang.Object userPhotoUrl_;
    /**
     * <code>optional string user_photo_url = 3;</code>
     */
    public java.lang.String getUserPhotoUrl() {
      java.lang.Object ref = userPhotoUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        userPhotoUrl_ = s;
        return s;
      }
    }
    /**
     * <code>optional string user_photo_url = 3;</code>
     */
    public com.google.protobuf.ByteString
        getUserPhotoUrlBytes() {
      java.lang.Object ref = userPhotoUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userPhotoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSiteUserIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, siteUserId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (!getUserPhotoUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, userPhotoUrl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSiteUserIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, siteUserId_);
      }
      if (!getUserNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (!getUserPhotoUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, userPhotoUrl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.site.UserFriendProto.FriendSimpleProfile)) {
        return super.equals(obj);
      }
      com.zaly.proto.site.UserFriendProto.FriendSimpleProfile other = (com.zaly.proto.site.UserFriendProto.FriendSimpleProfile) obj;

      boolean result = true;
      result = result && getSiteUserId()
          .equals(other.getSiteUserId());
      result = result && getUserName()
          .equals(other.getUserName());
      result = result && getUserPhotoUrl()
          .equals(other.getUserPhotoUrl());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + SITE_USER_ID_FIELD_NUMBER;
      hash = (53 * hash) + getSiteUserId().hashCode();
      hash = (37 * hash) + USER_NAME_FIELD_NUMBER;
      hash = (53 * hash) + getUserName().hashCode();
      hash = (37 * hash) + USER_PHOTO_URL_FIELD_NUMBER;
      hash = (53 * hash) + getUserPhotoUrl().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.site.UserFriendProto.FriendSimpleProfile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.FriendSimpleProfile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.FriendSimpleProfile)
        com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_FriendSimpleProfile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_FriendSimpleProfile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.class, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder.class);
      }

      // Construct using com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        siteUserId_ = "";

        userName_ = "";

        userPhotoUrl_ = "";

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_FriendSimpleProfile_descriptor;
      }

      public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile getDefaultInstanceForType() {
        return com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.getDefaultInstance();
      }

      public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile build() {
        com.zaly.proto.site.UserFriendProto.FriendSimpleProfile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile buildPartial() {
        com.zaly.proto.site.UserFriendProto.FriendSimpleProfile result = new com.zaly.proto.site.UserFriendProto.FriendSimpleProfile(this);
        result.siteUserId_ = siteUserId_;
        result.userName_ = userName_;
        result.userPhotoUrl_ = userPhotoUrl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.site.UserFriendProto.FriendSimpleProfile) {
          return mergeFrom((com.zaly.proto.site.UserFriendProto.FriendSimpleProfile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.site.UserFriendProto.FriendSimpleProfile other) {
        if (other == com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.getDefaultInstance()) return this;
        if (!other.getSiteUserId().isEmpty()) {
          siteUserId_ = other.siteUserId_;
          onChanged();
        }
        if (!other.getUserName().isEmpty()) {
          userName_ = other.userName_;
          onChanged();
        }
        if (!other.getUserPhotoUrl().isEmpty()) {
          userPhotoUrl_ = other.userPhotoUrl_;
          onChanged();
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.site.UserFriendProto.FriendSimpleProfile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.site.UserFriendProto.FriendSimpleProfile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object siteUserId_ = "";
      /**
       * <code>optional string site_user_id = 1;</code>
       */
      public java.lang.String getSiteUserId() {
        java.lang.Object ref = siteUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          siteUserId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string site_user_id = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSiteUserIdBytes() {
        java.lang.Object ref = siteUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          siteUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder setSiteUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        siteUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder clearSiteUserId() {
        
        siteUserId_ = getDefaultInstance().getSiteUserId();
        onChanged();
        return this;
      }
      /**
       * <code>optional string site_user_id = 1;</code>
       */
      public Builder setSiteUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        siteUserId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>optional string user_name = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_name = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 2;</code>
       */
      public Builder clearUserName() {
        
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_name = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userPhotoUrl_ = "";
      /**
       * <code>optional string user_photo_url = 3;</code>
       */
      public java.lang.String getUserPhotoUrl() {
        java.lang.Object ref = userPhotoUrl_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          userPhotoUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string user_photo_url = 3;</code>
       */
      public com.google.protobuf.ByteString
          getUserPhotoUrlBytes() {
        java.lang.Object ref = userPhotoUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userPhotoUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string user_photo_url = 3;</code>
       */
      public Builder setUserPhotoUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        userPhotoUrl_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_photo_url = 3;</code>
       */
      public Builder clearUserPhotoUrl() {
        
        userPhotoUrl_ = getDefaultInstance().getUserPhotoUrl();
        onChanged();
        return this;
      }
      /**
       * <code>optional string user_photo_url = 3;</code>
       */
      public Builder setUserPhotoUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        userPhotoUrl_ = value;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.FriendSimpleProfile)
    }

    // @@protoc_insertion_point(class_scope:site.FriendSimpleProfile)
    private static final com.zaly.proto.site.UserFriendProto.FriendSimpleProfile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.site.UserFriendProto.FriendSimpleProfile();
    }

    public static com.zaly.proto.site.UserFriendProto.FriendSimpleProfile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FriendSimpleProfile>
        PARSER = new com.google.protobuf.AbstractParser<FriendSimpleProfile>() {
      public FriendSimpleProfile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new FriendSimpleProfile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<FriendSimpleProfile> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FriendSimpleProfile> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GetFriendListResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:site.GetFriendListResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    java.util.List<com.zaly.proto.site.UserFriendProto.FriendSimpleProfile> 
        getListList();
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    com.zaly.proto.site.UserFriendProto.FriendSimpleProfile getList(int index);
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    int getListCount();
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    java.util.List<? extends com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder> 
        getListOrBuilderList();
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder getListOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code site.GetFriendListResponse}
   */
  public  static final class GetFriendListResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:site.GetFriendListResponse)
      GetFriendListResponseOrBuilder {
    // Use GetFriendListResponse.newBuilder() to construct.
    private GetFriendListResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private GetFriendListResponse() {
      list_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private GetFriendListResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                list_ = new java.util.ArrayList<com.zaly.proto.site.UserFriendProto.FriendSimpleProfile>();
                mutable_bitField0_ |= 0x00000001;
              }
              list_.add(
                  input.readMessage(com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = java.util.Collections.unmodifiableList(list_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.zaly.proto.site.UserFriendProto.GetFriendListResponse.class, com.zaly.proto.site.UserFriendProto.GetFriendListResponse.Builder.class);
    }

    public static final int LIST_FIELD_NUMBER = 1;
    private java.util.List<com.zaly.proto.site.UserFriendProto.FriendSimpleProfile> list_;
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    public java.util.List<com.zaly.proto.site.UserFriendProto.FriendSimpleProfile> getListList() {
      return list_;
    }
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    public java.util.List<? extends com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder> 
        getListOrBuilderList() {
      return list_;
    }
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    public int getListCount() {
      return list_.size();
    }
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile getList(int index) {
      return list_.get(index);
    }
    /**
     * <code>repeated .site.FriendSimpleProfile list = 1;</code>
     */
    public com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder getListOrBuilder(
        int index) {
      return list_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < list_.size(); i++) {
        output.writeMessage(1, list_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < list_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, list_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.zaly.proto.site.UserFriendProto.GetFriendListResponse)) {
        return super.equals(obj);
      }
      com.zaly.proto.site.UserFriendProto.GetFriendListResponse other = (com.zaly.proto.site.UserFriendProto.GetFriendListResponse) obj;

      boolean result = true;
      result = result && getListList()
          .equals(other.getListList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getListCount() > 0) {
        hash = (37 * hash) + LIST_FIELD_NUMBER;
        hash = (53 * hash) + getListList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.zaly.proto.site.UserFriendProto.GetFriendListResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code site.GetFriendListResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:site.GetFriendListResponse)
        com.zaly.proto.site.UserFriendProto.GetFriendListResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.zaly.proto.site.UserFriendProto.GetFriendListResponse.class, com.zaly.proto.site.UserFriendProto.GetFriendListResponse.Builder.class);
      }

      // Construct using com.zaly.proto.site.UserFriendProto.GetFriendListResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getListFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          listBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.zaly.proto.site.UserFriendProto.internal_static_site_GetFriendListResponse_descriptor;
      }

      public com.zaly.proto.site.UserFriendProto.GetFriendListResponse getDefaultInstanceForType() {
        return com.zaly.proto.site.UserFriendProto.GetFriendListResponse.getDefaultInstance();
      }

      public com.zaly.proto.site.UserFriendProto.GetFriendListResponse build() {
        com.zaly.proto.site.UserFriendProto.GetFriendListResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.zaly.proto.site.UserFriendProto.GetFriendListResponse buildPartial() {
        com.zaly.proto.site.UserFriendProto.GetFriendListResponse result = new com.zaly.proto.site.UserFriendProto.GetFriendListResponse(this);
        int from_bitField0_ = bitField0_;
        if (listBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            list_ = java.util.Collections.unmodifiableList(list_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.list_ = list_;
        } else {
          result.list_ = listBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.zaly.proto.site.UserFriendProto.GetFriendListResponse) {
          return mergeFrom((com.zaly.proto.site.UserFriendProto.GetFriendListResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.zaly.proto.site.UserFriendProto.GetFriendListResponse other) {
        if (other == com.zaly.proto.site.UserFriendProto.GetFriendListResponse.getDefaultInstance()) return this;
        if (listBuilder_ == null) {
          if (!other.list_.isEmpty()) {
            if (list_.isEmpty()) {
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureListIsMutable();
              list_.addAll(other.list_);
            }
            onChanged();
          }
        } else {
          if (!other.list_.isEmpty()) {
            if (listBuilder_.isEmpty()) {
              listBuilder_.dispose();
              listBuilder_ = null;
              list_ = other.list_;
              bitField0_ = (bitField0_ & ~0x00000001);
              listBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getListFieldBuilder() : null;
            } else {
              listBuilder_.addAllMessages(other.list_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.zaly.proto.site.UserFriendProto.GetFriendListResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.zaly.proto.site.UserFriendProto.GetFriendListResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<com.zaly.proto.site.UserFriendProto.FriendSimpleProfile> list_ =
        java.util.Collections.emptyList();
      private void ensureListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          list_ = new java.util.ArrayList<com.zaly.proto.site.UserFriendProto.FriendSimpleProfile>(list_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zaly.proto.site.UserFriendProto.FriendSimpleProfile, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder, com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder> listBuilder_;

      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public java.util.List<com.zaly.proto.site.UserFriendProto.FriendSimpleProfile> getListList() {
        if (listBuilder_ == null) {
          return java.util.Collections.unmodifiableList(list_);
        } else {
          return listBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public int getListCount() {
        if (listBuilder_ == null) {
          return list_.size();
        } else {
          return listBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile getList(int index) {
        if (listBuilder_ == null) {
          return list_.get(index);
        } else {
          return listBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder setList(
          int index, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.set(index, value);
          onChanged();
        } else {
          listBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder setList(
          int index, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.set(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder addList(com.zaly.proto.site.UserFriendProto.FriendSimpleProfile value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(value);
          onChanged();
        } else {
          listBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder addList(
          int index, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile value) {
        if (listBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureListIsMutable();
          list_.add(index, value);
          onChanged();
        } else {
          listBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder addList(
          com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder addList(
          int index, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder builderForValue) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.add(index, builderForValue.build());
          onChanged();
        } else {
          listBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder addAllList(
          java.lang.Iterable<? extends com.zaly.proto.site.UserFriendProto.FriendSimpleProfile> values) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, list_);
          onChanged();
        } else {
          listBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder clearList() {
        if (listBuilder_ == null) {
          list_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          listBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public Builder removeList(int index) {
        if (listBuilder_ == null) {
          ensureListIsMutable();
          list_.remove(index);
          onChanged();
        } else {
          listBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder getListBuilder(
          int index) {
        return getListFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder getListOrBuilder(
          int index) {
        if (listBuilder_ == null) {
          return list_.get(index);  } else {
          return listBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public java.util.List<? extends com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder> 
           getListOrBuilderList() {
        if (listBuilder_ != null) {
          return listBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(list_);
        }
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder addListBuilder() {
        return getListFieldBuilder().addBuilder(
            com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.getDefaultInstance());
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder addListBuilder(
          int index) {
        return getListFieldBuilder().addBuilder(
            index, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.getDefaultInstance());
      }
      /**
       * <code>repeated .site.FriendSimpleProfile list = 1;</code>
       */
      public java.util.List<com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder> 
           getListBuilderList() {
        return getListFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.zaly.proto.site.UserFriendProto.FriendSimpleProfile, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder, com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder> 
          getListFieldBuilder() {
        if (listBuilder_ == null) {
          listBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.zaly.proto.site.UserFriendProto.FriendSimpleProfile, com.zaly.proto.site.UserFriendProto.FriendSimpleProfile.Builder, com.zaly.proto.site.UserFriendProto.FriendSimpleProfileOrBuilder>(
                  list_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          list_ = null;
        }
        return listBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:site.GetFriendListResponse)
    }

    // @@protoc_insertion_point(class_scope:site.GetFriendListResponse)
    private static final com.zaly.proto.site.UserFriendProto.GetFriendListResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.zaly.proto.site.UserFriendProto.GetFriendListResponse();
    }

    public static com.zaly.proto.site.UserFriendProto.GetFriendListResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<GetFriendListResponse>
        PARSER = new com.google.protobuf.AbstractParser<GetFriendListResponse>() {
      public GetFriendListResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new GetFriendListResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<GetFriendListResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GetFriendListResponse> getParserForType() {
      return PARSER;
    }

    public com.zaly.proto.site.UserFriendProto.GetFriendListResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_GetFriendListRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_GetFriendListRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_FriendSimpleProfile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_FriendSimpleProfile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_site_GetFriendListResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_site_GetFriendListResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034site/api_getFriendList.proto\022\004site\",\n\024" +
      "GetFriendListRequest\022\024\n\014site_user_id\030\001 \001" +
      "(\t\"V\n\023FriendSimpleProfile\022\024\n\014site_user_i" +
      "d\030\001 \001(\t\022\021\n\tuser_name\030\002 \001(\t\022\026\n\016user_photo" +
      "_url\030\003 \001(\t\"@\n\025GetFriendListResponse\022\'\n\004l" +
      "ist\030\001 \003(\0132\031.site.FriendSimpleProfile2]\n\021" +
      "UserFriendService\022H\n\rgetFriendList\022\032.sit" +
      "e.GetFriendListRequest\032\033.site.GetFriendL" +
      "istResponseB&\n\023com.zaly.proto.siteB\017User" +
      "FriendProtob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_site_GetFriendListRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_site_GetFriendListRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_GetFriendListRequest_descriptor,
        new java.lang.String[] { "SiteUserId", });
    internal_static_site_FriendSimpleProfile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_site_FriendSimpleProfile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_FriendSimpleProfile_descriptor,
        new java.lang.String[] { "SiteUserId", "UserName", "UserPhotoUrl", });
    internal_static_site_GetFriendListResponse_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_site_GetFriendListResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_site_GetFriendListResponse_descriptor,
        new java.lang.String[] { "List", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
